version: "3.8"
name: uapi
services:
  postgres:
    image: postgres:latest
    hostname: ${DATABASE_HOST}
    container_name: uapi.db
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 15s
      timeout: 15s
      retries: 10
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
  node:
    image: alpine:latest
    hostname: app
    container_name: uapi.app
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./:/app
      - ./deploy/entrypoint.sh:/entrypoint.sh:ro
    working_dir: /app
    ports:
      - "${APP_PORT}:8181"
    ulimits:
      memlock: -1
    command: [ "/bin/sh", "/entrypoint.sh" ]
